### ISSUE TITLE
Add support to nodeAffinity

### ISSUE THREAD

**Issue by felipejfc** [topfreegames/maestro#4]
Reference:

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature

We need that to complement taints/tolerations.

Example from our monitoring pods:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "monitoring-dedicated"
                  operator: In
                  values: ["true"]
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
      containers:
      - name: prometheus
        image: quay.io/coreos/prometheus:v1.1.1
        ports:
        - name: web
          containerPort: 9090
```

This deployment will tolerate the taint ```dedicated:monitoring=NoSchedule``` while also only scheduling pods into nodes that has the selector ```monitoring-dedicates=true```

Taints and tolerations alone can't guarantee in which node the pods will be scheduled.
